-- Create canonical 3PL WMS schema (idempotent)

BEGIN;

CREATE SCHEMA IF NOT EXISTS ref;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS wh;
CREATE SCHEMA IF NOT EXISTS ops;
CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS wh.warehouses (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     varchar NOT NULL,
  address  varchar
);

CREATE TABLE IF NOT EXISTS wh.zones (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id integer NOT NULL REFERENCES wh.warehouses(id) ON DELETE RESTRICT,
  code         varchar NOT NULL,
  name         varchar,
  UNIQUE (warehouse_id, code)
);

CREATE TABLE IF NOT EXISTS wh.cells (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id integer NOT NULL REFERENCES wh.zones(id) ON DELETE RESTRICT,
  code    varchar NOT NULL,
  UNIQUE (zone_id, code)
);

CREATE TABLE IF NOT EXISTS core.clients (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  inn  varchar
);

CREATE TABLE IF NOT EXISTS core.users (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login      varchar NOT NULL UNIQUE,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS core.user_clients (
  user_id   integer NOT NULL REFERENCES core.users(id) ON DELETE RESTRICT,
  client_id integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  role      varchar NOT NULL,
  PRIMARY KEY (user_id, client_id)
);

CREATE TABLE IF NOT EXISTS core.products (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  sku       varchar NOT NULL,
  name      varchar NOT NULL,
  gtin      varchar,
  unit      varchar NOT NULL,
  UNIQUE (client_id, sku),
  UNIQUE (client_id, gtin)
);

CREATE TABLE IF NOT EXISTS ref.package_types (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT NULL UNIQUE,
  name varchar
);

CREATE TABLE IF NOT EXISTS ref.marking_code_statuses (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT NULL UNIQUE,
  name varchar
);

CREATE TABLE IF NOT EXISTS ref.package_statuses (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT NULL UNIQUE,
  name varchar
);

CREATE TABLE IF NOT EXISTS ref.doc_types (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT NULL UNIQUE,
  name varchar
);

CREATE TABLE IF NOT EXISTS ref.document_statuses (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT NULL UNIQUE,
  name varchar
);

CREATE TABLE IF NOT EXISTS ref.event_types (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT NULL UNIQUE,
  name varchar
);

CREATE TABLE IF NOT EXISTS ops.marking_codes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id  integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  product_id integer NOT NULL REFERENCES core.products(id) ON DELETE RESTRICT,
  fullcode   varchar NOT NULL,
  searchcode varchar NOT NULL,
  cell_id    integer REFERENCES wh.cells(id) ON DELETE RESTRICT,
  status_id  integer NOT NULL REFERENCES ref.marking_code_statuses(id) ON DELETE RESTRICT,
  created_at timestamp NOT NULL DEFAULT now(),
  UNIQUE (client_id, fullcode)
);

CREATE TABLE IF NOT EXISTS ops.packages (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  package_type_id integer NOT NULL REFERENCES ref.package_types(id) ON DELETE RESTRICT,
  fullcode        varchar NOT NULL,
  searchcode      varchar,
  cell_id         integer REFERENCES wh.cells(id) ON DELETE RESTRICT,
  status_id       integer NOT NULL REFERENCES ref.package_statuses(id) ON DELETE RESTRICT,
  created_at      timestamp NOT NULL DEFAULT now(),
  UNIQUE (client_id, fullcode)
);

CREATE TABLE IF NOT EXISTS ops.packages_history (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id         integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  parent_package_id integer NOT NULL REFERENCES ops.packages(id) ON DELETE RESTRICT,
  marking_code_id   bigint REFERENCES ops.marking_codes(id) ON DELETE RESTRICT,
  child_package_id  integer REFERENCES ops.packages(id) ON DELETE RESTRICT,
  added_at          timestamp NOT NULL DEFAULT now(),
  removed_at        timestamp,
  CONSTRAINT ck_packages_history_exactly_one_child
    CHECK (
      (marking_code_id IS NOT NULL AND child_package_id IS NULL) OR
      (marking_code_id IS NULL AND child_package_id IS NOT NULL)
    ),
  CONSTRAINT ck_packages_history_no_self_link
    CHECK (child_package_id IS NULL OR child_package_id <> parent_package_id)
);

CREATE TABLE IF NOT EXISTS ops.documents (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id    integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  doc_type_id  integer NOT NULL REFERENCES ref.doc_types(id) ON DELETE RESTRICT,
  status_id    integer NOT NULL REFERENCES ref.document_statuses(id) ON DELETE RESTRICT,
  created_by   integer NOT NULL REFERENCES core.users(id) ON DELETE RESTRICT,
  created_at   timestamp NOT NULL DEFAULT now(),
  completed_at timestamp
);

CREATE TABLE IF NOT EXISTS audit.events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id     integer NOT NULL REFERENCES core.clients(id) ON DELETE RESTRICT,
  document_id   integer REFERENCES ops.documents(id) ON DELETE SET NULL,
  event_type_id integer NOT NULL REFERENCES ref.event_types(id) ON DELETE RESTRICT,
  user_id       integer NOT NULL REFERENCES core.users(id) ON DELETE RESTRICT,
  created_at    timestamp NOT NULL DEFAULT now(),
  data          jsonb
);

COMMIT;

-- indexes
CREATE INDEX IF NOT EXISTS idx_marking_codes_client_searchcode
  ON ops.marking_codes (client_id, searchcode);
CREATE INDEX IF NOT EXISTS idx_marking_codes_client_status
  ON ops.marking_codes (client_id, status_id);
CREATE INDEX IF NOT EXISTS idx_marking_codes_client_product
  ON ops.marking_codes (client_id, product_id);

CREATE INDEX IF NOT EXISTS idx_packages_client_searchcode
  ON ops.packages (client_id, searchcode);
CREATE INDEX IF NOT EXISTS idx_packages_client_type
  ON ops.packages (client_id, package_type_id);
CREATE INDEX IF NOT EXISTS idx_packages_client_status
  ON ops.packages (client_id, status_id);

CREATE INDEX IF NOT EXISTS idx_packages_history_parent_active
  ON ops.packages_history (client_id, parent_package_id)
  WHERE removed_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_packages_history_active_marking_code
  ON ops.packages_history (client_id, marking_code_id)
  WHERE removed_at IS NULL AND marking_code_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_packages_history_active_child_package
  ON ops.packages_history (client_id, child_package_id)
  WHERE removed_at IS NULL AND child_package_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_packages_history_parent_added_at
  ON ops.packages_history (client_id, added_at);

CREATE INDEX IF NOT EXISTS idx_documents_client_status
  ON ops.documents (client_id, status_id);
CREATE INDEX IF NOT EXISTS idx_documents_client_type
  ON ops.documents (client_id, doc_type_id);
CREATE INDEX IF NOT EXISTS idx_documents_client_created
  ON ops.documents (client_id, created_at);

CREATE INDEX IF NOT EXISTS idx_events_document_created
  ON audit.events (document_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_client_created
  ON audit.events (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_user_created
  ON audit.events (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_client_type_created
  ON audit.events (client_id, event_type_id, created_at);

-- baseline dictionary values
INSERT INTO ref.package_types(code, name) VALUES
('BOX', 'Коробка'),
('PALLET', 'Палета'),
('UNIT', 'Штука')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref.marking_code_statuses(code, name) VALUES
('NEW', 'Новый'),
('IN_STOCK', 'На складе'),
('RESERVED', 'Зарезервирован'),
('SHIPPED', 'Отгружен'),
('LOST', 'Утерян')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref.package_statuses(code, name) VALUES
('OPEN', 'Открыта'),
('CLOSED', 'Закрыта'),
('SEALED', 'Опломбирована'),
('SHIPPED', 'Отгружена')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref.doc_types(code, name) VALUES
('RECEIPT', 'Приемка'),
('SHIPMENT', 'Отгрузка'),
('MOVE', 'Перемещение'),
('INVENTORY', 'Инвентаризация')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref.document_statuses(code, name) VALUES
('DRAFT', 'Черновик'),
('POSTED', 'Проведен'),
('CANCELLED', 'Отменен')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref.event_types(code, name) VALUES
('PACKAGE_CREATED', 'Создание упаковки'),
('PACK', 'Упаковка'),
('UNPACK', 'Разагрегация'),
('MOVE', 'Перемещение'),
('STATUS_CHANGE', 'Смена статуса'),
('DOC_POSTED', 'Проведение документа')
ON CONFLICT (code) DO NOTHING;
