services:
  mysql1:
    image: mysql/mysql-server:8.0
    container_name: mysql1
    hostname: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33101:3306"
    command: ["mysqld", "--server-id=201", "--log-bin=mysql-bin", "--gtid-mode=ON", "--enforce-gtid-consistency=ON", "--binlog-format=ROW", "--plugin-load-add=group_replication.so", "--transaction-write-set-extraction=XXHASH64", "--loose-group_replication_group_name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "--loose-group_replication_start_on_boot=OFF", "--loose-group_replication_local_address=mysql1:33061", "--loose-group_replication_group_seeds=mysql1:33061,mysql2:33061,mysql3:33061", "--loose-group_replication_bootstrap_group=OFF", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql1_data:/var/lib/mysql

  mysql2:
    image: mysql/mysql-server:8.0
    container_name: mysql2
    hostname: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33102:3306"
    command: ["mysqld", "--server-id=202", "--log-bin=mysql-bin", "--gtid-mode=ON", "--enforce-gtid-consistency=ON", "--binlog-format=ROW", "--plugin-load-add=group_replication.so", "--transaction-write-set-extraction=XXHASH64", "--loose-group_replication_group_name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "--loose-group_replication_start_on_boot=OFF", "--loose-group_replication_local_address=mysql2:33061", "--loose-group_replication_group_seeds=mysql1:33061,mysql2:33061,mysql3:33061", "--loose-group_replication_bootstrap_group=OFF", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql2_data:/var/lib/mysql

  mysql3:
    image: mysql/mysql-server:8.0
    container_name: mysql3
    hostname: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33103:3306"
    command: ["mysqld", "--server-id=203", "--log-bin=mysql-bin", "--gtid-mode=ON", "--enforce-gtid-consistency=ON", "--binlog-format=ROW", "--plugin-load-add=group_replication.so", "--transaction-write-set-extraction=XXHASH64", "--loose-group_replication_group_name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "--loose-group_replication_start_on_boot=OFF", "--loose-group_replication_local_address=mysql3:33061", "--loose-group_replication_group_seeds=mysql1:33061,mysql2:33061,mysql3:33061", "--loose-group_replication_bootstrap_group=OFF", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql3_data:/var/lib/mysql

volumes:
  mysql1_data:
  mysql2_data:
  mysql3_data:
